### ISSUE TITLE
Auto submiting form

### ISSUE THREAD

**Issue by sernuomorales** [craftpip/bootstrap-fullscreen-select#10]
Hi, 

I'm using your component inside a form, and clicking in the button that replaces the <select>, makes the form submit. 
You could avoid this by adding type="button" to the button tag. In other way, it behaves like a type="submit"

Thanks for this great component.

**Comment by sernuomorales** [comment]
I've noticed that in the uncompressed version this is already done, but not in the compressed version.

Thanks

**Comment by craftpip** [comment]
I will be updating the files soon.
Thanks !

**Comment by zerokewl88** [comment]
This still isn't applied today - and i had to manually add the 'type="button"' to the .js file as it initializes in order for this to work properly.
